import type { TreasureDefinition } from "@/lib/treasures/types"

/** 与 migration 20260530200000_treasures.sql seed 保持一致 */
export const TREASURE_DEFINITIONS: TreasureDefinition[] = [
  {
    id: "starry-elf",
    name: "星空精灵",
    icon: "✨",
    type: "pet",
    rarity: "legendary",
    description: "来自遥远星球的神秘生物",
    requirement: "完成《小王子》",
    conditionType: "book_complete",
    targetValue: 1,
    conditionPayload: { bookId: "1" },
    sortOrder: 10,
  },
  {
    id: "magic-cloak",
    name: "魔法斗篷",
    icon: "🧥",
    type: "skin",
    rarity: "epic",
    description: "隐身于黑夜的神奇披风",
    requirement: "收集30颗星星",
    conditionType: "stars_total",
    targetValue: 30,
    conditionPayload: {},
    sortOrder: 20,
  },
  {
    id: "reading-master",
    name: "阅读达人",
    icon: "🏅",
    type: "title",
    rarity: "rare",
    description: "展示你的阅读成就",
    requirement: "连续活跃7天",
    conditionType: "daily_streak",
    targetValue: 7,
    conditionPayload: {},
    sortOrder: 30,
  },
  {
    id: "mystic-island",
    name: "神秘岛屿",
    icon: "🏝️",
    type: "area",
    rarity: "legendary",
    description: "隐藏的冒险新大陆",
    requirement: "完成5次读后挑战",
    conditionType: "post_read_books_count",
    targetValue: 5,
    conditionPayload: {},
    sortOrder: 40,
  },
  {
    id: "dragon-egg",
    name: "龙蛋",
    icon: "🥚",
    type: "item",
    rarity: "epic",
    description: "沉睡的远古生命",
    requirement: "解锁3个区域",
    conditionType: "regions_unlocked",
    targetValue: 3,
    conditionPayload: {},
    sortOrder: 50,
  },
  {
    id: "rainbow-wings",
    name: "彩虹翅膀",
    icon: "🦋",
    type: "skin",
    rarity: "legendary",
    description: "七彩斑斓的飞行装备",
    requirement: "收集50颗星星",
    conditionType: "stars_total",
    targetValue: 50,
    conditionPayload: {},
    sortOrder: 60,
  },
  {
    id: "forest-guardian",
    name: "森林守护者",
    icon: "🌲",
    type: "title",
    rarity: "epic",
    description: "保护森林的勇士称号",
    requirement: "完成魔法森林",
    conditionType: "region_progress",
    targetValue: 100,
    conditionPayload: { regionId: "magic-forest" },
    sortOrder: 70,
  },
  {
    id: "crystal-ball",
    name: "水晶球",
    icon: "🔮",
    type: "item",
    rarity: "rare",
    description: "预见未来的神秘物品",
    requirement: "阅读10本不同书目",
    conditionType: "books_read_count",
    targetValue: 10,
    conditionPayload: {},
    sortOrder: 80,
  },
  {
    id: "mini-dragon",
    name: "小龙伙伴",
    icon: "🐉",
    type: "pet",
    rarity: "legendary",
    description: "忠诚勇敢的小龙",
    requirement: "完成天空王国",
    conditionType: "region_progress",
    targetValue: 100,
    conditionPayload: { regionId: "sky-kingdom" },
    sortOrder: 90,
  },
  {
    id: "adventurer-badge",
    name: "冒险家徽章",
    icon: "🎖️",
    type: "badge",
    rarity: "rare",
    description: "勇敢冒险者的证明",
    requirement: "解锁3个区域",
    conditionType: "regions_unlocked",
    targetValue: 3,
    conditionPayload: {},
    sortOrder: 100,
  },
  {
    id: "magic-hat",
    name: "魔法帽",
    icon: "🎩",
    type: "skin",
    rarity: "epic",
    description: "充满魔力的帽子",
    requirement: "连续活跃14天",
    conditionType: "daily_streak",
    targetValue: 14,
    conditionPayload: {},
    sortOrder: 110,
  },
  {
    id: "ocean-heart",
    name: "海洋之心",
    icon: "💎",
    type: "item",
    rarity: "legendary",
    description: "来自深海的珍贵宝石",
    requirement: "完成深海遗迹",
    conditionType: "region_progress",
    targetValue: 100,
    conditionPayload: { regionId: "ocean-ruins" },
    sortOrder: 120,
  },
]

export const TREASURE_HOME_PREVIEW_IDS = [
  "starry-elf",
  "magic-cloak",
  "reading-master",
  "mystic-island",
  "dragon-egg",
] as const
